# Generated by Django 4.2 on 2023-04-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Typing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('difficulty', models.TextField()),
                ('displayText', models.TextField()),
                ('inputText', models.TextField()),
            ],
        ),
    ]
